# originally stolen from https://jekyllrb.com/docs/continuous-integration/github-actions/
# <3

name: Build site and commit to gh-pages branch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: "checking out..."
        uses: actions/checkout@v3

      - name: "setting up node…"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run fetch:charts
      - run: npm run build

      - name: "deploy!"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: 'gh-pages'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          
